## configurations

YEAR = 2023

TRANSACTION_FILENAME_FORMAT = "TOML"

TRANSACTION_DIRECTORY = f"{YEAR}"
TRANSACTION_FILENAME = "expenses.toml"
TRANSACTION_FILEPATH = f"{TRANSACTION_DIRECTORY}/{TRANSACTION_FILENAME}"

FONT_FAMILY = "DejaVu Sans"
FONT_SIZE = 22

XTICK_SIZE = 20

CATEGORY_QUANTITY_KEY = 0
CATEGORY_PRICE_KEY = 1
